/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import cadastro.UtilitarioLogin;
import controle.ControladorTelaInicial;
import java.awt.event.ActionListener;

/**
 *
 * @author 88178
 */
public class TelaInicial extends javax.swing.JFrame implements ControladorTelaInicial.Display{

    private ControladorTelaInicial controle;
    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        controle = new ControladorTelaInicial(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPaciente = new javax.swing.JButton();
        btnVisitante = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        btnPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tela/hospital32.png"))); // NOI18N
        btnPaciente.setText("Lista de pacientes");
        jPanel1.add(btnPaciente);

        btnVisitante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tela/stethoscope.png"))); // NOI18N
        btnVisitante.setText("Visitantes");
        jPanel1.add(btnVisitante);

        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tela/heart8.png"))); // NOI18N
        btnUsuario.setText("Cadastro");
        jPanel1.add(btnUsuario);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tela/Philips.png"))); // NOI18N
        getContentPane().add(jLabel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPaciente;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JButton btnVisitante;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addAcaoCadastro(ActionListener listener) {
        btnUsuario.addActionListener(listener);
    }

    @Override
    public void addAcaoListarPacientes(ActionListener listener) {
        btnPaciente.addActionListener(listener);
    }

    @Override
    public void addAcaoVisitante(ActionListener listener) {
        btnVisitante.addActionListener(listener);
    }

    @Override
    public void setVisibilidadeCadastro(boolean visibilidade) {
        btnUsuario.setEnabled(visibilidade);
    }

    @Override
    public void setVisibilidadeListarPacientes(boolean visibilidade) {
        btnPaciente.setEnabled(visibilidade);
    }

    @Override
    public void setVisibilidadeVisitantes(boolean visibilidade) {
        btnVisitante.setEnabled(visibilidade);
    }

    @Override
    public void fecharTela() {
        dispose();
    }
}
